three:
	cp ../../three.js-master/build/three.js .
	cp ../../three.js/examples/js/controls/OrbitControls.js .
	cp ../../three.js/examples/js/libs/dat.gui.min.js .
	cp ../../three.js/examples/js/libs/stats.min.js .
